gui:
  # nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#ff9900'
      - bold
    inactiveBorderColor:
      - '#666666'
    optionsTextColor:
      - '#cccccc'
    selectedLineBgColor:
      - '#003366'
    unstagedChangesColor:
      - '#990000'
    stagedChangesColor:
      - '#660066'
    defaultFgColor:
      - white
    # cherryPickedCommitBgColor:
    #   - '#458588'
    # cherryPickedCommitFgColor:
    #   - '#83a598'
